# Generated by Django 6.0.5 on 2026-05-28 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_alter_globalpermission_options_and_more'),
        ('activities', '0002_activity_duration_minutes_activity_location_and_more'),
        ('contacts', '0002_contact_organization'),
        ('deals', '0001_initial'),
        ('leads', '0002_lead_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_date']},
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['deal', 'activity_date'], name='activities__deal_id_d15cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'activity_date'], name='activities__organiz_e7df72_idx'),
        ),
    ]
