# Generated by Django 6.0.3 on 2026-03-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessrequest',
            name='access_type',
            field=models.CharField(choices=[('user', 'User'), ('department', 'Department')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataaccessrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_user_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
