# Generated by Django 6.0.3 on 2026-03-25 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_globalpermission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='globalpermission',
            options={'permissions': [('view_department_data', 'Can view department data'), ('approve_access_request', 'Can approve access requests')]},
        ),
        migrations.AddField(
            model_name='dataaccessrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataaccessrequest',
            name='access_type',
            field=models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('department', 'Department')], max_length=20),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.department')),
                ('permissions', models.ManyToManyField(blank=True, related_name='custom_groups', to='auth.permission')),
                ('users', models.ManyToManyField(blank=True, related_name='crm_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataaccessrequest',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
        migrations.AddConstraint(
            model_name='dataaccessrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_user__isnull', False), ('target_group__isnull', True), ('target_department__isnull', True)), models.Q(('target_user__isnull', True), ('target_group__isnull', False), ('target_department__isnull', True)), models.Q(('target_user__isnull', True), ('target_group__isnull', True), ('target_department__isnull', False)), _connector='OR'), name='only_one_access_target'),
        ),
        migrations.AddConstraint(
            model_name='dataaccessrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'target_user'), name='unique_user_access_request'),
        ),
        migrations.AddConstraint(
            model_name='dataaccessrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'target_group'), name='unique_group_access_request'),
        ),
        migrations.AddConstraint(
            model_name='dataaccessrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'target_department'), name='unique_department_access_request'),
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('department', 'name')},
        ),
    ]
