# Generated by Django 6.0.3 on 2026-03-25 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_organization_alter_globalpermission_options_and_more'),
        ('companies', '0002_company_organization'),
        ('contacts', '0002_contact_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('is_closed_stage', models.BooleanField(default=False)),
                ('is_won_stage', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='deals.pipeline')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='companies.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='contacts.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.organization')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('pipeline_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='deals.pipelinestage')),
            ],
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['organization'], name='deals_pipel_organiz_4e256c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='pipelinestage',
            index=models.Index(fields=['pipeline', 'order'], name='deals_pipel_pipelin_7b8eb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('pipeline', 'order')},
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization'], name='deals_deal_organiz_6d9c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner'], name='deals_deal_owner_i_f2c1d9_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['pipeline_stage'], name='deals_deal_pipelin_443cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status'], name='deals_deal_status_06cb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='deals_deal_created_9d9de4_idx'),
        ),
    ]
